"""
See COPYRIGHT.md for copyright information.

TaxonomyEmitter, InstanceEmitter, Testcase/IndexEmitter.

TaxonomyEmitter writes one ``taxonomies/gen-<key>.xsd`` per unique type
key, re-basing the tested datatype onto the matching ``xbrli:*ItemType`` via
``complexType/simpleContent/restriction``.

The original facet children are reproduced under the ``xsd:`` prefix (localName +
all attributes preserved); the source namespace-prefix pollution carried by the
verbatim ``facet_xml`` (e.g. ``xmlns="<instance-ns>"``) is dropped so the emitted
schema is clean and deterministic. The xbrli import ``schemaLocation`` is pinned to
the canonical URL from ``XbrlConst`` — the wrong URL collapses the concept to
``anyType``.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from lxml import etree

from xbrl_xsdtests.model import (
    ExtractedType,
    ExtractedValue,
    InstanceTestRef,
    TypeKey,
    Variation,
)

XSD_NS = "http://www.w3.org/2001/XMLSchema"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
XBRLI_NS = "http://www.xbrl.org/2003/instance"
LINK_NS = "http://www.xbrl.org/2003/linkbase"
XLINK_NS = "http://www.w3.org/1999/xlink"
XBRLI_SCHEMA_LOCATION = "http://www.xbrl.org/2003/xbrl-instance-2003-12-31.xsd"

# Native Arelle conformance format.
CONFORMANCE_NS = "http://xbrl.org/2005/conformance"
# The prefix on the expected error must resolve to this namespace so Arelle's
# grader (Validate.py) maps ``xmlSchema:valueError`` to an XDT schema error
# (ModelTestcaseObject.expected builds a QName against the testcase nsmap).
XML_SCHEMA_ERROR_NS = "http://www.xbrl.org/2005/genericXmlSchemaError"
INDEX_NAME = "XBRL_XSTS_VALUES"
INDEX_FILENAME = "index.xml"
EXPECTED_ERROR = "xmlSchema:valueError"
_TESTCASE_OWNER = "support@arelle.org"
# Stable (timestamp-free, so output stays reproducible) generation-details header.
_GENERATED_NOTE = (
    "Generated by the XSTS value/facet conformance generator "
    "(python -m xbrl_xsdtests); "
    "do not edit by hand, regenerate with python -m xbrl_xsdtests."
)

CONCEPT_NAME = "t"
TYPE_NAME = "tType"
_GEN_NS_PREFIX = "http://arelle.org/xsts-value-suite/"

# Fixed dummy context/unit values.
_CONTEXT_ID = "c"
_UNIT_ID = "u"
_ENTITY_SCHEME = "http://example.com/entity"
_ENTITY_IDENTIFIER = "e"
_INSTANT = "2020-01-01"
_PURE_MEASURE = "xbrli:pure"
_DECIMALS = "INF"

_UNSAFE = re.compile(r"[^A-Za-z0-9._-]")


def gen_namespace(key: TypeKey) -> str:
    """Target namespace for a generated per-type taxonomy (unique per type key)."""
    return f"{_GEN_NS_PREFIX}{key.value}"


def taxonomy_filename(key: TypeKey) -> str:
    return f"gen-{key.value}.xsd"


def _sanitize(text: str) -> str:
    return _UNSAFE.sub("_", text)


def category(t: ExtractedType) -> str:
    """Coarse output bucket grouping all types sharing an xsd base primitive."""
    return _sanitize(t.base_xsd)


def variation_id(ref: InstanceTestRef) -> str:
    """Globally-unique, stable, filesystem-safe id for an instanceTest.

    XSTS instance names alone are not unique (e.g. Sun reuses ``Positive``), so the
    id folds in contributor + testGroup name, which together are unique.
    """
    return _sanitize(f"{ref.group.source.contributor}_{ref.group.name}_{ref.name}")


def instance_filename(ref: InstanceTestRef) -> str:
    return f"{variation_id(ref)}.xbrl"


def instance_path(out: Path, ref: InstanceTestRef, key: TypeKey, t: ExtractedType) -> Path:
    return out / category(t) / key.value / instance_filename(ref)


def testcase_filename(key: TypeKey) -> str:
    return f"{key.value}-testcase.xml"


def testcase_uri(t: ExtractedType, key: TypeKey) -> str:
    """Index-relative POSIX path of a testcase file (one per emitted type key)."""
    return f"{category(t)}/{testcase_filename(key)}"


def testcase_path(out: Path, t: ExtractedType, key: TypeKey) -> Path:
    return out / category(t) / testcase_filename(key)


def _instance_href(ref: InstanceTestRef, key: TypeKey) -> str:
    """Instance path relative to its testcase file (both live in ``<category>/``)."""
    return f"{key.value}/{instance_filename(ref)}"


class TaxonomyEmitter:
    """Emits the re-based per-datatype taxonomy (one concept ``t`` per file)."""

    def emit(self, key: TypeKey, t: ExtractedType, out: Path) -> Path:
        gen_ns = gen_namespace(key)
        nsmap = {"xsd": XSD_NS, "xbrli": XBRLI_NS, "gen": gen_ns}
        schema = etree.Element(f"{{{XSD_NS}}}schema", nsmap=nsmap)
        schema.set("targetNamespace", gen_ns)
        schema.set("elementFormDefault", "qualified")

        imp = etree.SubElement(schema, f"{{{XSD_NS}}}import")
        imp.set("namespace", XBRLI_NS)
        imp.set("schemaLocation", XBRLI_SCHEMA_LOCATION)

        element = etree.SubElement(schema, f"{{{XSD_NS}}}element")
        element.set("name", CONCEPT_NAME)
        element.set("id", CONCEPT_NAME)
        element.set("type", f"gen:{TYPE_NAME}")
        element.set("substitutionGroup", "xbrli:item")
        element.set(f"{{{XBRLI_NS}}}periodType", "instant")
        element.set("abstract", "false")
        element.set("nillable", "true")

        complex_type = etree.SubElement(schema, f"{{{XSD_NS}}}complexType")
        complex_type.set("name", TYPE_NAME)
        simple_content = etree.SubElement(complex_type, f"{{{XSD_NS}}}simpleContent")
        restriction = etree.SubElement(simple_content, f"{{{XSD_NS}}}restriction")
        restriction.set("base", f"xbrli:{t.xbrli_item_type}")
        for facet_xml in t.facet_xml:
            self._append_facet(restriction, facet_xml)

        out_dir = out / "taxonomies"
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / taxonomy_filename(key)
        path.write_bytes(
            etree.tostring(etree.ElementTree(schema), pretty_print=True, xml_declaration=True, encoding="UTF-8")
        )
        return path

    @staticmethod
    def _append_facet(restriction: etree._Element, facet_xml: str) -> None:
        source = etree.fromstring(facet_xml.encode("utf-8"))
        local = etree.QName(source).localname
        facet = etree.SubElement(restriction, f"{{{XSD_NS}}}{local}")
        for name, value in source.attrib.items():
            facet.set(name, value)


class InstanceEmitter:
    """Emits one XBRL instance (``.xbrl``) carrying the tested value(s) as fact(s).

    A source document may hold several occurrences of the tested element (e.g.
    Microsoft's ``maxOccurs``-repeated probes); each occurrence becomes its own fact
    of the single generated concept, sharing one context (and one unit, for numeric
    types), so the instance is invalid exactly when some occurrence is invalid —
    reproducing the source document's whole-document validity.

    Numeric facts get an ``xbrli:pure`` unit + ``decimals="INF"``; non-numeric facts
    get neither. Nil values set ``xsi:nil`` and omit ``decimals``.
    Namespace declarations carried by QName values are copied onto the root so the
    value's prefix resolves (the structural xbrli/link/xlink/gen prefixes win on the
    astronomically-unlikely clash).
    """

    def emit(
        self,
        ref: InstanceTestRef,
        values: list[ExtractedValue],
        key: TypeKey,
        t: ExtractedType,
        out: Path,
    ) -> Path:
        gen_ns = gen_namespace(key)
        nsmap: dict[str | None, str] = {}
        for value in values:
            nsmap.update(value.extra_nsmap)
        nsmap.update({"xbrli": XBRLI_NS, "link": LINK_NS, "xlink": XLINK_NS, "gen": gen_ns})
        if any(value.is_nil for value in values):
            nsmap["xsi"] = XSI_NS

        root = etree.Element(f"{{{XBRLI_NS}}}xbrl", nsmap=nsmap)

        path = instance_path(out, ref, key, t)
        schema_ref = etree.SubElement(root, f"{{{LINK_NS}}}schemaRef")
        schema_ref.set(f"{{{XLINK_NS}}}type", "simple")
        schema_ref.set(f"{{{XLINK_NS}}}href", self._schema_ref_href(out, path, key))

        self._append_context(root)
        if t.numeric:
            self._append_unit(root)
        for value in values:
            self._append_fact(root, gen_ns, t, value)

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(
            etree.tostring(etree.ElementTree(root), pretty_print=True, xml_declaration=True, encoding="UTF-8")
        )
        return path

    @staticmethod
    def _schema_ref_href(out: Path, path: Path, key: TypeKey) -> str:
        taxonomy = out / "taxonomies" / taxonomy_filename(key)
        return Path(os.path.relpath(taxonomy, start=path.parent)).as_posix()

    @staticmethod
    def _append_context(root: etree._Element) -> None:
        context = etree.SubElement(root, f"{{{XBRLI_NS}}}context")
        context.set("id", _CONTEXT_ID)
        entity = etree.SubElement(context, f"{{{XBRLI_NS}}}entity")
        identifier = etree.SubElement(entity, f"{{{XBRLI_NS}}}identifier")
        identifier.set("scheme", _ENTITY_SCHEME)
        identifier.text = _ENTITY_IDENTIFIER
        period = etree.SubElement(context, f"{{{XBRLI_NS}}}period")
        instant = etree.SubElement(period, f"{{{XBRLI_NS}}}instant")
        instant.text = _INSTANT

    @staticmethod
    def _append_unit(root: etree._Element) -> None:
        unit = etree.SubElement(root, f"{{{XBRLI_NS}}}unit")
        unit.set("id", _UNIT_ID)
        measure = etree.SubElement(unit, f"{{{XBRLI_NS}}}measure")
        measure.text = _PURE_MEASURE

    @staticmethod
    def _append_fact(root: etree._Element, gen_ns: str, t: ExtractedType, value: ExtractedValue) -> None:
        fact = etree.SubElement(root, f"{{{gen_ns}}}{CONCEPT_NAME}")
        fact.set("contextRef", _CONTEXT_ID)
        if t.numeric:
            fact.set("unitRef", _UNIT_ID)
        if value.is_nil:
            fact.set(f"{{{XSI_NS}}}nil", "true")
        else:
            if t.numeric:
                fact.set("decimals", _DECIMALS)
            fact.text = value.text


@dataclass(frozen=True)
class _VariationRecord:
    """A variation plus the XSTS source files it was generated from (for provenance)."""

    variation: Variation
    taxonomy: str           # generated, deduped taxonomy filename (gen-<key>.xsd)
    source_instance: str    # repo-relative path of the originating XSTS instance .xml
    source_schema: str      # repo-relative path of the originating XSTS schema .xsd
    contributor: str
    group: str


@dataclass
class _TestcaseAccum:
    """Mutable accumulator for the variations grouped under one testcase file."""

    name: str
    taxonomy: str
    records: list[_VariationRecord] = field(default_factory=list)
    _ids: set[str] = field(default_factory=set)

    def add(self, record: _VariationRecord) -> None:
        vid = record.variation.id
        if vid in self._ids:
            raise ValueError(f"duplicate variation id {vid!r} in testcase {self.name!r}")
        self._ids.add(vid)
        self.records.append(record)


def _safe_comment(text: str) -> str:
    """Make ``text`` safe as XML comment content (no ``--`` and no trailing ``-``).

    A space is inserted after any hyphen that is immediately followed by another
    (handling runs of 3+), and the content is wrapped in spaces so it can never end
    with a hyphen — both forbidden in XML comments.
    """
    return f" {re.sub(r'-(?=-)', '- ', text)} "


class IndexEmitter:
    """Accumulates variations and writes the native conformance testcases + index.

    One ``*-testcase.xml`` is written per emitted type key (variations grouped by
    type, since per-type ≈ per-testGroup). The testcase namespace is
    ``http://xbrl.org/2005/conformance``; invalid values expect
    ``<error>xmlSchema:valueError</error>`` and valid values an empty ``<result/>``
    (match-all semantics). ``index.xml`` is written **last** — after every
    referenced testcase file exists — so the harness never hits a dangling
    ``<testcase uri>``.

    Every generated file carries a generation-details header comment, and each
    variation is preceded by a comment naming the XSTS instance and schema it was
    generated from (so a deduped testcase's variations stay traceable to source).
    """

    def __init__(self, name: str = INDEX_NAME) -> None:
        self._name = name
        self._testcases: dict[str, _TestcaseAccum] = {}
        self._variation_ids: set[str] = set()

    def add_variation(self, t: ExtractedType, key: TypeKey, ref: InstanceTestRef) -> None:
        """Register one instanceTest as a variation under its type's testcase."""
        uri = testcase_uri(t, key)
        accum = self._testcases.get(uri)
        if accum is None:
            accum = _TestcaseAccum(name=key.value, taxonomy=taxonomy_filename(key))
            self._testcases[uri] = accum
        vid = variation_id(ref)
        if vid in self._variation_ids:
            raise ValueError(f"duplicate variation id across suite: {vid!r}")
        self._variation_ids.add(vid)
        accum.add(
            _VariationRecord(
                variation=Variation(
                    id=vid,
                    instance_href=_instance_href(ref, key),
                    expected_error=EXPECTED_ERROR if ref.validity == "invalid" else None,
                ),
                taxonomy=taxonomy_filename(key),
                source_instance=ref.instance_member,
                source_schema=ref.group.schema_member,
                contributor=ref.group.source.contributor,
                group=ref.group.name,
            )
        )

    def write(self, out: Path) -> list[Path]:
        """Write all testcase files then ``index.xml`` last; return testcase paths."""
        written: list[Path] = []
        for uri in sorted(self._testcases):
            path = out / uri
            self._write_testcase(path, self._testcases[uri])
            written.append(path)
        self._write_index(out)
        return written

    def _write_testcase(self, path: Path, accum: _TestcaseAccum) -> None:
        nsmap = {None: CONFORMANCE_NS, "xmlSchema": XML_SCHEMA_ERROR_NS}
        root = etree.Element(f"{{{CONFORMANCE_NS}}}testcase", nsmap=nsmap)
        root.set("name", accum.name)
        root.set("owner", _TESTCASE_OWNER)
        header = (
            f"{_GENERATED_NOTE} Type key: {accum.name}; "
            f"taxonomy: taxonomies/{accum.taxonomy}; variations: {len(accum.records)}."
        )
        root.addprevious(etree.Comment(_safe_comment(header)))
        for record in accum.records:
            self._append_variation(root, record)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(
            etree.tostring(etree.ElementTree(root), pretty_print=True, xml_declaration=True, encoding="UTF-8")
        )

    @staticmethod
    def _append_variation(root: etree._Element, record: _VariationRecord) -> None:
        provenance = (
            f"{record.contributor} {record.group} | "
            f"source instance: {record.source_instance} | "
            f"source schema: {record.source_schema}"
        )
        root.append(etree.Comment(_safe_comment(provenance)))
        variation = record.variation
        element = etree.SubElement(root, f"{{{CONFORMANCE_NS}}}variation")
        element.set("id", variation.id)
        data = etree.SubElement(element, f"{{{CONFORMANCE_NS}}}data")
        instance = etree.SubElement(data, f"{{{CONFORMANCE_NS}}}instance")
        instance.set("readMeFirst", "true")
        instance.text = variation.instance_href
        result = etree.SubElement(element, f"{{{CONFORMANCE_NS}}}result")
        if variation.expected_error is not None:
            error = etree.SubElement(result, f"{{{CONFORMANCE_NS}}}error")
            error.text = variation.expected_error

    def _write_index(self, out: Path) -> None:
        root = etree.Element("testcases")
        root.set("name", self._name)
        total_variations = sum(len(accum.records) for accum in self._testcases.values())
        header = (
            f"{_GENERATED_NOTE} {len(self._testcases)} testcases; "
            f"{total_variations} variations. Each <testcase> file carries per-variation "
            "comments naming the XSTS instance/schema it was generated from."
        )
        root.addprevious(etree.Comment(_safe_comment(header)))
        for uri in sorted(self._testcases):
            testcase = etree.SubElement(root, "testcase")
            testcase.set("uri", uri)
        out.mkdir(parents=True, exist_ok=True)
        (out / INDEX_FILENAME).write_bytes(
            etree.tostring(etree.ElementTree(root), pretty_print=True, xml_declaration=True, encoding="UTF-8")
        )
